/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.proyectoBDA.agencia_fiscal.PRESENTACION;

/**
 *
 * @author hisam
 */
public class CostoLicencia extends javax.swing.JFrame {

    /**
     * Creates new form CostoLicencia
     */
    public CostoLicencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCostoLicencia = new javax.swing.JLabel();
        lblVigencia = new javax.swing.JLabel();
        lblCosto1 = new javax.swing.JLabel();
        lblSeleccion = new javax.swing.JLabel();
        lbl1anio1 = new javax.swing.JLabel();
        lbl2anios = new javax.swing.JLabel();
        lbl3anios = new javax.swing.JLabel();
        jbtn1anio = new javax.swing.JRadioButton();
        lbl1anio2 = new javax.swing.JLabel();
        lbl1anio3 = new javax.swing.JLabel();
        lbl1anio4 = new javax.swing.JLabel();
        jbtn2anios = new javax.swing.JRadioButton();
        jbtn3anios = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        flechaIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCostoLicencia1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Costo de licencias");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("____________________________________________________________________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lblCostoLicencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCostoLicencia.setForeground(new java.awt.Color(65, 34, 52));
        lblCostoLicencia.setText("Costo de licencias");
        jPanel1.add(lblCostoLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        lblVigencia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblVigencia.setForeground(new java.awt.Color(109, 70, 107));
        lblVigencia.setText("Vigencia");
        jPanel1.add(lblVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, -1));

        lblCosto1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCosto1.setForeground(new java.awt.Color(109, 70, 107));
        lblCosto1.setText("Costo");
        jPanel1.add(lblCosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 50, -1));

        lblSeleccion.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblSeleccion.setForeground(new java.awt.Color(109, 70, 107));
        lblSeleccion.setText("Seleccion");
        jPanel1.add(lblSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 70, -1));

        lbl1anio1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl1anio1.setText("$1,100");
        jPanel1.add(lbl1anio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        lbl2anios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl2anios.setText("2 años");
        jPanel1.add(lbl2anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, -1));

        lbl3anios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl3anios.setText("3 años");
        jPanel1.add(lbl3anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, -1));

        jbtn1anio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jbtn1anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        lbl1anio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl1anio2.setText("1 año");
        jPanel1.add(lbl1anio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 40, -1));

        lbl1anio3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl1anio3.setText("$600");
        jPanel1.add(lbl1anio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        lbl1anio4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl1anio4.setText("$900");
        jPanel1.add(lbl1anio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jbtn2anios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jbtn2anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jbtn3anios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jbtn3anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel2.setText("____________________________________________________________________________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(65, 34, 52));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 123, 31));

        flechaIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        flechaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.jpg"))); // NOI18N
        jPanel1.add(flechaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 40, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 550, 330));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 50));

        lblCostoLicencia1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCostoLicencia1.setForeground(new java.awt.Color(109, 70, 107));
        lblCostoLicencia1.setText("Historial licencias y placas");
        jPanel2.add(lblCostoLicencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel flechaIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jbtn1anio;
    private javax.swing.JRadioButton jbtn2anios;
    private javax.swing.JRadioButton jbtn3anios;
    private javax.swing.JLabel lbl1anio1;
    private javax.swing.JLabel lbl1anio2;
    private javax.swing.JLabel lbl1anio3;
    private javax.swing.JLabel lbl1anio4;
    private javax.swing.JLabel lbl2anios;
    private javax.swing.JLabel lbl3anios;
    private javax.swing.JLabel lblCosto1;
    private javax.swing.JLabel lblCostoLicencia;
    private javax.swing.JLabel lblCostoLicencia1;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JLabel lblVigencia;
    // End of variables declaration//GEN-END:variables
}
