/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.proyectoBDA.agencia_fiscal;

/**
 *
 * @author hisam
 */
public class CostoLicencia extends javax.swing.JFrame {

    /**
     * Creates new form CostoLicencia
     */
    public CostoLicencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn1anio = new javax.swing.JRadioButton();
        lblCostoLicencia = new javax.swing.JLabel();
        lbl2anios = new javax.swing.JLabel();
        lblSeleccion = new javax.swing.JLabel();
        jbtn3anios = new javax.swing.JRadioButton();
        lbl3anios = new javax.swing.JLabel();
        lblCosto1 = new javax.swing.JLabel();
        jbtn2anios = new javax.swing.JRadioButton();
        lbl1anio1 = new javax.swing.JLabel();
        lblVigencia = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Costo de licencias");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jbtn1anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        lblCostoLicencia.setFont(new java.awt.Font("Inter ExtraBold", 0, 18)); // NOI18N
        lblCostoLicencia.setForeground(new java.awt.Color(65, 34, 52));
        lblCostoLicencia.setText("Costo de licencias");
        jPanel1.add(lblCostoLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        lbl2anios.setFont(new java.awt.Font("Inter ExtraBold", 0, 15)); // NOI18N
        lbl2anios.setText("2 años");
        jPanel1.add(lbl2anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 60, -1));

        lblSeleccion.setFont(new java.awt.Font("Inter ExtraBold", 0, 15)); // NOI18N
        lblSeleccion.setForeground(new java.awt.Color(65, 34, 52));
        lblSeleccion.setText("Seleccion");
        jPanel1.add(lblSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 100, -1));
        jPanel1.add(jbtn3anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        lbl3anios.setFont(new java.awt.Font("Inter ExtraBold", 0, 15)); // NOI18N
        lbl3anios.setText("3 años");
        jPanel1.add(lbl3anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 60, -1));

        lblCosto1.setFont(new java.awt.Font("Inter ExtraBold", 0, 15)); // NOI18N
        lblCosto1.setForeground(new java.awt.Color(65, 34, 52));
        lblCosto1.setText("Costo");
        jPanel1.add(lblCosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 60, -1));
        jPanel1.add(jbtn2anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        lbl1anio1.setFont(new java.awt.Font("Inter ExtraBold", 0, 15)); // NOI18N
        lbl1anio1.setText("1 año");
        jPanel1.add(lbl1anio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 40, -1));

        lblVigencia.setFont(new java.awt.Font("Inter ExtraBold", 0, 15)); // NOI18N
        lblVigencia.setForeground(new java.awt.Color(65, 34, 52));
        lblVigencia.setText("Vigencia");
        jPanel1.add(lblVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, -1));

        jButton1.setBackground(new java.awt.Color(65, 34, 52));
        jButton1.setFont(new java.awt.Font("Inter ExtraBold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 123, 31));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costo_de_licencias.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jbtn1anio;
    private javax.swing.JRadioButton jbtn2anios;
    private javax.swing.JRadioButton jbtn3anios;
    private javax.swing.JLabel lbl1anio1;
    private javax.swing.JLabel lbl2anios;
    private javax.swing.JLabel lbl3anios;
    private javax.swing.JLabel lblCosto1;
    private javax.swing.JLabel lblCostoLicencia;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JLabel lblVigencia;
    // End of variables declaration//GEN-END:variables
}
